version: 2.1
orbs:
    snyk: snyk/snyk@0.0.8
    slack: circleci/slack@3.4.2
jobs:
    build-test-monitor:
        docker:
            - image: circleci/node:14
        steps:
            - slack/notify:
                channel: C0137E8F72A
                color: '#42e2f4'
                message: Starting snyk-api-import build-test-monitor job
            - checkout
            - run: npm install && npm run build
            - run: npm run test:integration
            - run: npm run test:system
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: true
                token-variable: SNYK_TOKEN_PROD
            - run: npx semantic-release
            - slack/status:
                fail_only: true
                only_for_branches: master
    build-test:
        docker:
            - image: circleci/node:14
        steps:
            - slack/notify:
                channel: C0137E8F72A
                color: '#42e2f4'
                message: Starting snyk-api-import build-test job
            - checkout
            - run: npm install && npm run build
            - run: npm run lint
            - run: npm run test:integration
            - run: npm run test:system
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: false
                token-variable: SNYK_TOKEN_PROD
            - run: npx tsc
            - run: npm run pkg-binaries-linux
            - run: ./snyk-api-import-linux help
            - slack/status:
                fail_only: true
                only_for_branches: master
workflows:
    version: 2
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
            - build-test-monitor:
                context: SNYK

    build-test-monitor:
        jobs:
            - build-test-monitor:
                context: SNYK
                filters:
                    branches:
                        only:
                            - master
    build-test:
        jobs:
            - build-test:
                context: SNYK
                filters:
                    branches:
                        ignore:
                        - master
                        - /pull\/[0-9]+/
